### PR TITLE
[fix] Revision of the "lv_apps" submodule shall be specified.

### PR DESCRIPTION
**Pull request by BesitzeRuf**
Revision of the "lv_apps" submodule shall be specified in .gitmodules. Otherwise it is not possible to update "lv_app" submodule from the list.

### CODE REVIEW

**Comment by kisvegabor** [comment]
`lv_apps` is already deprecated and replaced by `lv_examples`.

Do you use an older version of LVGL?

**Comment by BesitzeRuf** [comment]
Hi, thanks for reply. Now it is clear for me. The comments in readme file of the [lv_app](https://github.com/lvgl/lv_apps/tree/74618912deb430f0e49e76bbda394c9c5e810ebd) confused me. So in this case I will create other pull request (the lv_app shall be removed from the file ".gitmodules").

**Comment by BesitzeRuf** [comment]
I closed this pull request, because submodule [lv_app](https://github.com/lvgl/lv_apps/tree/74618912deb430f0e49e76bbda394c9c5e810ebd) is deprecated.

**Comment by kisvegabor** [comment]
Ah, it's really confusing. I've just cleaned up lv_apps' README.

**Pull request closed without merging**
